name: Test

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: The First
        run: |
          echo Hello
          
  test2:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: The Second
        run: echo Good Bye

  Biderie:
    needs: [test2]
    uses: ./.github/workflows/ghcr.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  Chelouterie:
    needs: [Biderie]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit